import 'package:flutter/material.dart';

import '../../../../core/theme/app_colors.dart';
import '../../domain/entities/document_branding_entity.dart';

/// The Declarations tab body — mirrors `DocumentBrandingPanel.tsx`'s
/// declarations list (6 selectable rows, each showing a truncated current
/// value or "Not set") + the selected field's editable textarea with its
/// own local "Save changes" button.
class DocumentBrandingDeclarations extends StatelessWidget {
  final Map<String, dynamic> draft;
  final String selectedKey;
  final bool saving;
  final ValueChanged<String> onSelect;
  final void Function(String key, String value) onChanged;
  final VoidCallback onSave;

  const DocumentBrandingDeclarations({
    super.key,
    required this.draft,
    required this.selectedKey,
    required this.saving,
    required this.onSelect,
    required this.onChanged,
    required this.onSave,
  });

  @override
  Widget build(BuildContext context) {
    final selectedField = documentBrandingDeclarationFields.firstWhere((f) => f.key == selectedKey);
    final selectedValue = (draft[selectedKey] as String?) ?? '';

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text('Declarations', style: TextStyle(fontSize: 12.5, fontWeight: FontWeight.w600, color: AppColors.textSecondary)),
        const SizedBox(height: 8),
        for (final field in documentBrandingDeclarationFields) _row(field),
        const SizedBox(height: 18),
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Icon(Icons.description_outlined, size: 15, color: AppColors.textSecondary),
            const SizedBox(width: 8),
            Expanded(
              child: Text(selectedField.label, style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: AppColors.textPrimary)),
            ),
          ],
        ),
        const SizedBox(height: 4),
        Text(
          'Printed on every ${selectedField.label} PDF generated by the ERP.',
          style: const TextStyle(fontSize: 11.5, color: AppColors.textTertiary),
        ),
        const SizedBox(height: 10),
        _DeclarationTextArea(
          // A fresh controller per declaration is intentional (switching
          // fields is a hard reset); within one field, `_DeclarationTextArea`
          // keeps its own controller alive across rebuilds so typing doesn't
          // reset the cursor to the start on every keystroke.
          key: ValueKey(selectedKey),
          initialValue: selectedValue,
          hintText: selectedField.placeholder,
          onChanged: (v) => onChanged(selectedKey, v),
        ),
        const SizedBox(height: 8),
        const Text(
          'Use {studentName} / {staffName} where applicable — replaced automatically at print time.',
          style: TextStyle(fontSize: 11, color: AppColors.textTertiary, height: 1.4),
        ),
        const SizedBox(height: 14),
        Align(
          alignment: Alignment.centerRight,
          child: ElevatedButton(
            onPressed: saving ? null : onSave,
            style: ElevatedButton.styleFrom(
              backgroundColor: AppColors.purpleAccent,
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 10),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
            ),
            child: saving
                ? const Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      SizedBox(width: 14, height: 14, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white)),
                      SizedBox(width: 8),
                      Text('Saving…', style: TextStyle(fontSize: 13, fontWeight: FontWeight.w700)),
                    ],
                  )
                : const Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(Icons.check_circle, size: 15),
                      SizedBox(width: 6),
                      Text('Save changes', style: TextStyle(fontSize: 13, fontWeight: FontWeight.w700)),
                    ],
                  ),
          ),
        ),
      ],
    );
  }

  Widget _row(({String key, String label, String placeholder}) field) {
    final value = (draft[field.key] as String?) ?? '';
    final isSet = value.trim().isNotEmpty;
    final selected = field.key == selectedKey;
    return InkWell(
      onTap: () => onSelect(field.key),
      borderRadius: BorderRadius.circular(9),
      child: Container(
        margin: const EdgeInsets.only(bottom: 6),
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
        decoration: BoxDecoration(
          color: selected ? AppColors.purpleTint : AppColors.bgPrimary,
          border: Border.all(color: selected ? AppColors.purpleAccent : AppColors.borderSecondary),
          borderRadius: BorderRadius.circular(9),
        ),
        child: Row(
          children: [
            const Icon(Icons.description_outlined, size: 15, color: AppColors.textSecondary),
            const SizedBox(width: 10),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(field.label, style: const TextStyle(fontSize: 12.5, fontWeight: FontWeight.w700, color: AppColors.textPrimary)),
                  const SizedBox(height: 1),
                  Text(
                    isSet ? value : 'Not set',
                    style: const TextStyle(fontSize: 11, color: AppColors.textTertiary),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                  ),
                ],
              ),
            ),
            if (isSet)
              Container(width: 6, height: 6, margin: const EdgeInsets.only(left: 6), decoration: const BoxDecoration(color: AppColors.purpleAccent, shape: BoxShape.circle)),
          ],
        ),
      ),
    );
  }
}

class _DeclarationTextArea extends StatefulWidget {
  final String initialValue;
  final String hintText;
  final ValueChanged<String> onChanged;

  const _DeclarationTextArea({super.key, required this.initialValue, required this.hintText, required this.onChanged});

  @override
  State<_DeclarationTextArea> createState() => _DeclarationTextAreaState();
}

class _DeclarationTextAreaState extends State<_DeclarationTextArea> {
  late final TextEditingController _controller = TextEditingController(text: widget.initialValue);

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return TextField(
      controller: _controller,
      onChanged: widget.onChanged,
      maxLines: null,
      minLines: 10,
      style: const TextStyle(fontSize: 13, color: AppColors.textPrimary, height: 1.5),
      decoration: InputDecoration(
        isDense: true,
        hintText: widget.hintText,
        hintStyle: const TextStyle(fontSize: 13, color: AppColors.textTertiary),
        contentPadding: const EdgeInsets.all(12),
        filled: true,
        fillColor: AppColors.bgPrimary,
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(10), borderSide: const BorderSide(color: AppColors.borderSecondary)),
        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(10), borderSide: const BorderSide(color: AppColors.borderSecondary)),
        focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(10), borderSide: const BorderSide(color: AppColors.purpleAccent)),
      ),
    );
  }
}
